export function createDefaultReport(companyName = '', fiscalYear = 2025) {
  const now = new Date().toISOString();
  const reportId = `report_${Date.now()}`;

  return {
    metadata: {
      report_version: '1.0',
      report_id: reportId,
      created_at: now,
      updated_at: now,
      created_by: '',
      status: 'Entwurf',
      reporting_framework: 'ESRS',
      reporting_period: String(fiscalYear),
      fiscal_year_start: `${fiscalYear}-01-01`,
      fiscal_year_end: `${fiscalYear}-12-31`,
      external_assurance: false,
      assurance_provider: '',
      assurance_level: '',
    },
    organization: {
      name: companyName,
      legal_form: '',
      registration_number: '',
      fiscal_year: fiscalYear,
      reporting_period_start: `${fiscalYear}-01-01`,
      reporting_period_end: `${fiscalYear}-12-31`,
      revenue: 0,
      employees_total: 0,
      employees_fte: 0,
      locations: [],
      headquarters: '',
      certifications: [],
      business_model: '',
      main_products_services: '',
      target_markets: '',
      value_chain_description: '',
      nace_code: '',
      industry_sector: '',
      sustainability_contact: '',
      sustainability_email: '',
      management_report: '',
      esg_management_system: '',
      reporting_framework: 'ESRS (freiwillig)',
      reporting_scope: '',
      consolidation_scope: '',
      subsidiaries_included: false,
      subsidiaries_description: '',
      material_omissions: '',
      estimates_uncertainties: '',
      transition_provisions: '',
      external_assurance: 'Keine',
      assurance_provider: '',
    },
    materiality: {
      stakeholders: [],
      topics: [
        { topic: 'E1 - Klimawandel', is_material: false, impact_description: '', impact_score: 0, financial_description: '', financial_score: 0, justification: '', data_sources: [], assessed_by: '', assessed_date: null, approved_by: '' },
        { topic: 'E2 - Umweltverschmutzung', is_material: false, impact_description: '', impact_score: 0, financial_description: '', financial_score: 0, justification: '', data_sources: [], assessed_by: '', assessed_date: null, approved_by: '' },
        { topic: 'E3 - Wasser- und Meeresressourcen', is_material: false, impact_description: '', impact_score: 0, financial_description: '', financial_score: 0, justification: '', data_sources: [], assessed_by: '', assessed_date: null, approved_by: '' },
        { topic: 'E4 - Biodiversität und Ökosysteme', is_material: false, impact_description: '', impact_score: 0, financial_description: '', financial_score: 0, justification: '', data_sources: [], assessed_by: '', assessed_date: null, approved_by: '' },
        { topic: 'E5 - Kreislaufwirtschaft', is_material: false, impact_description: '', impact_score: 0, financial_description: '', financial_score: 0, justification: '', data_sources: [], assessed_by: '', assessed_date: null, approved_by: '' },
        { topic: 'S1 - Eigene Belegschaft', is_material: false, impact_description: '', impact_score: 0, financial_description: '', financial_score: 0, justification: '', data_sources: [], assessed_by: '', assessed_date: null, approved_by: '' },
        { topic: 'S2 - Arbeitskräfte in der Wertschöpfungskette', is_material: false, impact_description: '', impact_score: 0, financial_description: '', financial_score: 0, justification: '', data_sources: [], assessed_by: '', assessed_date: null, approved_by: '' },
        { topic: 'S3 - Betroffene Gemeinschaften', is_material: false, impact_description: '', impact_score: 0, financial_description: '', financial_score: 0, justification: '', data_sources: [], assessed_by: '', assessed_date: null, approved_by: '' },
        { topic: 'S4 - Verbraucher und Endnutzer', is_material: false, impact_description: '', impact_score: 0, financial_description: '', financial_score: 0, justification: '', data_sources: [], assessed_by: '', assessed_date: null, approved_by: '' },
        { topic: 'G1 - Unternehmenspolitik', is_material: false, impact_description: '', impact_score: 0, financial_description: '', financial_score: 0, justification: '', data_sources: [], assessed_by: '', assessed_date: null, approved_by: '' },
      ],
      impact_threshold: 30.0,
      financial_threshold: 12.0,
      methodology: '',
      process_description: '',
      approval_body: '',
      approval_date: null,
    },
    iro_summary: {
      assessments: [
        { topic: 'E1 - Klimawandel', topic_code: 'E1', impacts: [], risks: [], opportunities: [], responsible_person: '', assessment_date: null, decision_body: '', approval_date: null, review_cycle: 'Jährlich', data_sources: [], assumptions: '', limitations: '' },
        { topic: 'E2 - Umweltverschmutzung', topic_code: 'E2', impacts: [], risks: [], opportunities: [], responsible_person: '', assessment_date: null, decision_body: '', approval_date: null, review_cycle: 'Jährlich', data_sources: [], assumptions: '', limitations: '' },
        { topic: 'E3 - Wasser- und Meeresressourcen', topic_code: 'E3', impacts: [], risks: [], opportunities: [], responsible_person: '', assessment_date: null, decision_body: '', approval_date: null, review_cycle: 'Jährlich', data_sources: [], assumptions: '', limitations: '' },
        { topic: 'E4 - Biodiversität und Ökosysteme', topic_code: 'E4', impacts: [], risks: [], opportunities: [], responsible_person: '', assessment_date: null, decision_body: '', approval_date: null, review_cycle: 'Jährlich', data_sources: [], assumptions: '', limitations: '' },
        { topic: 'E5 - Kreislaufwirtschaft', topic_code: 'E5', impacts: [], risks: [], opportunities: [], responsible_person: '', assessment_date: null, decision_body: '', approval_date: null, review_cycle: 'Jährlich', data_sources: [], assumptions: '', limitations: '' },
        { topic: 'S1 - Eigene Belegschaft', topic_code: 'S1', impacts: [], risks: [], opportunities: [], responsible_person: '', assessment_date: null, decision_body: '', approval_date: null, review_cycle: 'Jährlich', data_sources: [], assumptions: '', limitations: '' },
        { topic: 'S2 - Arbeitskräfte in der Wertschöpfungskette', topic_code: 'S2', impacts: [], risks: [], opportunities: [], responsible_person: '', assessment_date: null, decision_body: '', approval_date: null, review_cycle: 'Jährlich', data_sources: [], assumptions: '', limitations: '' },
        { topic: 'S3 - Betroffene Gemeinschaften', topic_code: 'S3', impacts: [], risks: [], opportunities: [], responsible_person: '', assessment_date: null, decision_body: '', approval_date: null, review_cycle: 'Jährlich', data_sources: [], assumptions: '', limitations: '' },
        { topic: 'S4 - Verbraucher und Endnutzer', topic_code: 'S4', impacts: [], risks: [], opportunities: [], responsible_person: '', assessment_date: null, decision_body: '', approval_date: null, review_cycle: 'Jährlich', data_sources: [], assumptions: '', limitations: '' },
        { topic: 'G1 - Unternehmenspolitik', topic_code: 'G1', impacts: [], risks: [], opportunities: [], responsible_person: '', assessment_date: null, decision_body: '', approval_date: null, review_cycle: 'Jährlich', data_sources: [], assumptions: '', limitations: '' },
      ],
      impact_threshold: 30.0,
      risk_opportunity_threshold: 12.0,
    },
    environmental: {
      e1_climate: {
        energy: { total_kwh: 0, renewable_kwh: 0, non_renewable_kwh: 0, electricity_kwh: 0, natural_gas_kwh: 0, heating_oil_kwh: 0, district_heating_kwh: 0, solar_kwh: 0, other_kwh: 0, other_description: '' },
        emissions: { scope1_total: 0, scope1_stationary: 0, scope1_mobile: 0, scope1_fugitive: 0, scope1_process: 0, scope2_total: 0, scope2_location_based: 0, scope2_market_based: 0, scope2_electricity: 0, scope2_heating: 0, scope2_cooling: 0, scope3_total: 0, scope3_purchased_goods: 0, scope3_capital_goods: 0, scope3_fuel_energy: 0, scope3_upstream_transport: 0, scope3_waste: 0, scope3_business_travel: 0, scope3_commuting: 0, scope3_upstream_leased: 0, scope3_downstream_transport: 0, scope3_processing: 0, scope3_use_of_products: 0, scope3_end_of_life: 0, scope3_downstream_leased: 0, scope3_franchises: 0, scope3_investments: 0 },
        emissions_per_revenue: 0, emissions_per_employee: 0, energy_per_revenue: 0,
        has_transition_plan: false, transition_plan_description: '', net_zero_target_year: null, interim_targets: [],
        carbon_credits_purchased: 0, carbon_credits_retired: 0,
        methodology: '', base_year: 2024, verification_status: '',
      },
      e2_pollution: { air_pollutants_tonnes: 0, nox_emissions: 0, sox_emissions: 0, pm_emissions: 0, voc_emissions: 0, water_pollutants_tonnes: 0, wastewater_volume_m3: 0, soil_contamination_incidents: 0, substances_of_concern: [], pollution_prevention_measures: '', is_relevant: false, relevance_justification: '' },
      e3_water: { total_water_withdrawal_m3: 0, water_from_municipal: 0, water_from_groundwater: 0, water_from_surface: 0, water_from_rainwater: 0, water_recycled_m3: 0, total_water_discharge_m3: 0, operations_in_water_stress_areas: false, water_stress_locations: [], is_relevant: false, relevance_justification: '' },
      e4_biodiversity: { total_land_area_ha: 0, sealed_land_area_ha: 0, operations_near_protected_areas: false, protected_area_details: '', biodiversity_measures: '', restoration_projects: '', significant_impacts: '', is_relevant: false, relevance_justification: '' },
      e5_circular_economy: { total_material_input_tonnes: 0, recycled_material_input_tonnes: 0, renewable_material_input_tonnes: 0, total_waste_tonnes: 0, hazardous_waste_tonnes: 0, non_hazardous_waste_tonnes: 0, waste_recycled_tonnes: 0, waste_landfill_tonnes: 0, waste_incinerated_tonnes: 0, products_designed_for_circularity: '', take_back_programs: '', hardware_recycling_program: false, hardware_recycled_units: 0, hardware_refurbished_units: 0, e_waste_tonnes: 0, is_relevant: true, relevance_justification: '' },
      environmental_management_system: '',
      environmental_certifications: [],
    },
    social: {
      s1_own_workforce: {
        demographics: { total_employees: 0, permanent_employees: 0, temporary_employees: 0, full_time_employees: 0, part_time_employees: 0, fte: 0, female_employees: 0, male_employees: 0, diverse_employees: 0, female_percentage: 0, under_30: 0, age_30_50: 0, over_50: 0, total_management: 0, female_management: 0, female_management_percentage: 0, board_members: 0, female_board_members: 0, employees_germany: 0, employees_eu: 0, employees_non_eu: 0 },
        health_safety: { work_accidents: 0, work_accidents_per_1000: 0, fatal_accidents: 0, near_misses: 0, lost_days_accidents: 0, sick_days_total: 0, sick_days_per_employee: 0, occupational_illness_cases: 0, safety_trainings_conducted: 0, employees_trained_safety: 0, risk_assessments_completed: 0, health_safety_certifications: [], health_programs: '', mental_health_support: '' },
        training: { total_training_hours: 0, training_hours_per_employee: 0, training_hours_female: 0, training_hours_male: 0, training_hours_management: 0, training_investment_eur: 0, training_investment_per_employee: 0, technical_training_hours: 0, soft_skills_training_hours: 0, compliance_training_hours: 0, leadership_training_hours: 0, apprenticeship_positions: 0, apprentices_current: 0, mentoring_program: false, career_development_programs: '' },
        compensation: { gender_pay_gap_percentage: 0, pay_gap_methodology: '', above_minimum_wage_percentage: 100, living_wage_commitment: false, employees_with_benefits: 0, pension_coverage_percentage: 0, health_insurance_coverage: 0, ceo_to_median_ratio: null },
        engagement: { engagement_survey_conducted: false, survey_participation_rate: 0, engagement_score: null, voluntary_turnover_rate: 0, involuntary_turnover_rate: 0, new_hires: 0, internal_promotions: 0, collective_agreement_coverage: 0, works_council_exists: false, grievances_filed: 0, grievances_resolved: 0 },
        hr_policies: '', diversity_policy: '', anti_discrimination_policy: '', work_life_balance_measures: '', remote_work_policy: '',
      },
      s2_supply_chain: { total_suppliers: 0, critical_suppliers: 0, suppliers_by_region: {}, suppliers_screened: 0, suppliers_with_coc: 0, suppliers_audited: 0, high_risk_suppliers: 0, human_rights_issues_identified: 0, corrective_actions_taken: 0, supplier_relationships_terminated: 0, supplier_code_of_conduct: '', human_rights_due_diligence: '', supplier_assessment_criteria: '', key_suppliers: [], is_relevant: true, relevance_justification: '' },
      s3_affected_communities: { community_engagement_activities: '', stakeholder_dialogues: 0, positive_impacts: '', negative_impacts: '', indigenous_peoples_affected: false, community_investment_eur: 0, donations_eur: 0, volunteering_hours: 0, local_hiring_percentage: 0, local_procurement_percentage: 0, community_grievance_mechanism: false, community_complaints: 0, is_relevant: false, relevance_justification: '' },
      s4_consumers: { product_safety_incidents: 0, product_recalls: 0, safety_certifications: [], data_privacy_policy: '', data_breaches: 0, data_subjects_affected: 0, gdpr_complaints: 0, privacy_training_employees: 0, security_incidents: 0, security_certifications: [], penetration_tests_conducted: 0, customer_satisfaction_score: null, customer_complaints: 0, complaints_resolved: 0, accessible_products_services: '', accessibility_measures: '', ai_systems_deployed: false, ai_ethics_policy: '', ai_transparency_measures: '', is_relevant: true, relevance_justification: '' },
      social_management_approach: '',
    },
    governance: {
      g1_business_conduct: {
        board: { board_size: 0, executive_directors: 0, non_executive_directors: 0, independent_directors: 0, female_board_members: 0, female_percentage: 0, age_diversity: '', expertise_diversity: '', audit_committee: false, sustainability_committee: false, risk_committee: false, nomination_committee: false, remuneration_committee: false, sustainability_responsibility: '', sustainability_expertise: '', sustainability_reporting_frequency: '' },
        compliance: { code_of_conduct_exists: false, code_of_conduct_coverage: 0, code_of_conduct_training_coverage: 0, anti_corruption_policy: false, anti_corruption_training_coverage: 0, corruption_risk_assessment: false, corruption_incidents: 0, compliance_violations: 0, fines_paid_eur: 0, legal_proceedings: 0, political_contributions_eur: 0, lobbying_activities: '', transparency_register: false },
        whistleblower: { whistleblower_system_exists: false, system_description: '', anonymous_reporting_possible: false, external_channel_available: false, reports_received: 0, reports_investigated: 0, reports_substantiated: 0, reports_resolved: 0, retaliation_cases: 0, whistleblower_protection_policy: false, reports_by_category: {} },
        data_security: { iso_27001_certified: false, tisax_certified: false, soc2_certified: false, other_certifications: [], security_incidents_total: 0, security_incidents_critical: 0, data_breaches: 0, personal_data_affected: 0, financial_impact_eur: 0, incidents_reported_to_authorities: 0, average_response_time_hours: 0, security_training_coverage: 0, penetration_tests_per_year: 0, vulnerability_assessments_per_year: 0, security_audits: 0 },
        ai_governance: { ai_systems_in_use: false, ai_systems_description: '', high_risk_ai_systems: 0, ai_ethics_policy: false, ai_risk_assessment_conducted: false, human_oversight_measures: '', ai_disclosure_to_users: false, ai_training_for_employees: false, eu_ai_act_compliance_status: '' },
        controversial_sectors: { is_relevant: false, fossil_fuels: false, fossil_fuels_revenue_pct: 0, tobacco: false, tobacco_revenue_pct: 0, weapons: false, weapons_revenue_pct: 0, controversial_weapons: false, gambling: false, nuclear: false, justification: '' },
        risk_management_system: '', esg_risk_integration: '', risk_assessment_frequency: '',
        stakeholder_engagement_policy: '', stakeholder_engagement_activities: '',
        sustainability_policy: '', environmental_policy: '', human_rights_policy: '', supplier_policy: '',
        due_diligence_process: '', due_diligence_findings: '', remediation_actions: '',
        management_systems: [], external_audits: '',
      },
      governance_notes: '',
    },
    policies: [],
    actions: [],
    targets: [],
    esrs_index: [],
  };
}
